### ISSUE TITLE
执行make时候报错，怎么解决？

### ISSUE THREAD

**Issue by lucas7788** [DNAProject/DNA#422]
![default](https://user-images.githubusercontent.com/13885466/34508296-af506336-f078-11e7-84fe-ff47a6531c79.png)

**Comment by Honglei-Cong** [comment]
`make` is OK now.

**Comment by Xunzhuo** [comment]
![error](https://user-images.githubusercontent.com/48784001/102383596-b1172e80-4006-11eb-8a4b-bcde771f6a49.png)
Hi, errors occurs when i make DNA~ I need help for this~Tks

**Comment by qiluge** [comment]
> ![error](https://user-images.githubusercontent.com/48784001/102383596-b1172e80-4006-11eb-8a4b-bcde771f6a49.png)
> Hi, errors occurs when i make DNA~ I need help for this~Tks

It looks like there's something wrong with your network. Please check your network and goproxy, or other go env.

**Comment by Xunzhuo** [comment]
> > ![error](https://user-images.githubusercontent.com/48784001/102383596-b1172e80-4006-11eb-8a4b-bcde771f6a49.png)
> > Hi, errors occurs when i make DNA~ I need help for this~Tks
> 
> It looks like there's something wrong with your network. Please check your network and goproxy, or other go env

Tks, after changing goproxy, problem solved
