### ISSUE TITLE
contract deploy failed when the node using different port config

### ISSUE THREAD

**Issue by chenquanyu** [DNAProject/DNA#446]
Start node with the following ports, then run `./dnaNode contract deploy`.
![image](https://user-images.githubusercontent.com/4393234/85119962-24590700-b255-11ea-8792-9164572c04db.png)

**Comment by Honglei-Cong** [comment]
You started 3 DnaNode process, their rpc ports are 22336 23336 24336.
But these rpc ports are not used when deploying smart contract.

Please configure rpcport with `--rpc-port=22336` in your deploying command.

**Comment by chenquanyu** [comment]
![image](https://user-images.githubusercontent.com/4393234/85370152-dd268b00-b560-11ea-92bb-d2ed6c9a0f0c.png)

It is OK when using --rpcport parameter, thanks.
